# vazifa -9

# For if missing qiymatlarni toldirish

In [92]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].filna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=true)

In [93]:
df.head(10)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,0.564103,0.322,0.293919,0.777778,No,0.8,0.777778,0.8,No
1,CLG0061,0.478632,0.104,0.140203,0.777778,No,0.7,0.777778,0.0,No
2,CLG0036,0.581197,0.072,0.217905,0.888889,No,0.3,0.000000,0.2,No
3,CLG0055,0.692308,0.094,0.204392,0.555556,Yes,0.1,0.555556,0.2,No
4,CLG0004,0.470085,0.582,0.532095,0.666667,No,0.8,1.000000,0.4,No
5,CLG0015,0.470085,0.052,0.131757,0.666667,No,0.5,0.777778,0.0,No
6,CLG0071,0.700855,0.336,0.344595,0.444444,No,0.7,0.777778,0.4,Yes
7,CLG0096,0.598291,0.754,0.712838,0.666667,No,0.3,0.000000,0.4,Yes
8,CLG0097,0.435897,0.294,0.302365,0.888889,No,0.7,0.777778,1.0,No
9,CLG0057,0.572650,0.764,0.685811,0.333333,No,0.5,0.888889,0.2,No

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  float64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  float64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  float64
 7   Communication_Skills    10000 non-null  float64
 8   Projects_Completed      10000 non-null  float64
 9   Placement               10000 non-null  object
dtypes: float64(7), object(3)
memory usage: 781.4+ KB

# For + Encoding

In [96]:
df.nunique()

College_ID                100
IQ                        104
Prev_Sem_Result           501
CGPA                      590
Academic_Performance       10
Internship_Experience       2
Extra_Curricular_Score     11
Communication_Skills       10
Projects_Completed          6
Placement                   2
dtype: int64

In [97]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=2:
            dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
            df=pd.concat([df.drop(columns=col),dummies], axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [98]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Internship_Experience_No,Internship_Experience_Yes,Placement_No,Placement_Yes
0,29,0.564103,0.322,0.293919,0.777778,0.8,0.777778,0.8,1,0,1,0
1,60,0.478632,0.104,0.140203,0.777778,0.7,0.777778,0.0,1,0,1,0
2,35,0.581197,0.072,0.217905,0.888889,0.3,0.000000,0.2,1,0,1,0
3,54,0.692308,0.094,0.204392,0.555556,0.1,0.555556,0.2,0,1,1,0
4,3,0.470085,0.582,0.532095,0.666667,0.8,1.000000,0.4,1,0,1,0

In [56]:
import pandas as pd

In [57]:
df=pd.read_csv('chicken_meat_freshness.csv')

In [58]:
for col in df.columns:
    print(col)

Category
Shelf_Life_Day
Sensor_1
Sensor_2
Sensor_3
Sensor_4
Sensor_5
Sensor_6
Sensor_7
Sensor_8
Sensor_9
Sensor_10
Mean_Value
Variance
Target

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        1000 non-null   object
 1   Shelf_Life_Day  1000 non-null   int64
 2   Sensor_1        1000 non-null   float64
 3   Sensor_2        1000 non-null   float64
 4   Sensor_3        1000 non-null   float64
 5   Sensor_4        1000 non-null   float64
 6   Sensor_5        1000 non-null   float64
 7   Sensor_6        1000 non-null   float64
 8   Sensor_7        1000 non-null   float64
 9   Sensor_8        1000 non-null   float64
 10  Sensor_9        1000 non-null   float64
 11  Sensor_10       1000 non-null   float64
 12  Mean_Value      1000 non-null   float64
 13  Variance        1000 non-null   float64
 14  Target          1000 non-null   object
dtypes: float64(12), int64(1), object(2)
memory usage: 117.3+ KB

In [60]:
df.nunique()

Category             2
Shelf_Life_Day       5
Sensor_1          1000
Sensor_2          1000
Sensor_3          1000
Sensor_4          1000
Sensor_5          1000
Sensor_6          1000
Sensor_7          1000
Sensor_8          1000
Sensor_9          1000
Sensor_10         1000
Mean_Value        1000
Variance          1000
Target              10
dtype: int64

In [61]:
df.head()

,Category,Shelf_Life_Day,Sensor_1,Sensor_2,Sensor_3,Sensor_4,Sensor_5,Sensor_6,Sensor_7,Sensor_8,Sensor_9,Sensor_10,Mean_Value,Variance,Target
0,Fresh,0,0.604967,0.598617,0.606477,0.615230,0.597658,0.597659,0.615792,0.607674,0.595305,0.605426,0.604481,0.000047,Fresh_Day0
1,Fresh,0,0.595366,0.595343,0.602420,0.580867,0.582751,0.594377,0.589872,0.603142,0.590920,0.585877,0.592093,0.000051,Fresh_Day0
2,Fresh,0,0.614656,0.597742,0.600675,0.585753,0.594556,0.601109,0.588490,0.603757,0.593994,0.597083,0.597782,0.000060,Fresh_Day0
3,Fresh,0,0.593983,0.618523,0.599865,0.589423,0.608225,0.587792,0.602089,0.580403,0.586718,0.601969,0.596899,0.000118,Fresh_Day0
4,Fresh,0,0.607385,0.601714,0.598844,0.596989,0.585215,0.592802,0.595394,0.610571,0.603436,0.582370,0.597472,0.000073,Fresh_Day0

# SCALING

In [63]:
from sklearn.preprocessing import MinMaxScaler

In [64]:
minmaxscaler=MinMaxScaler()

In [65]:
minmaxscaler

MinMaxScaler()

In [67]:
df['Sensor_1']=minmaxscaler.fit_transform(df[['Sensor_1']])

In [68]:
df.head()

,Category,Shelf_Life_Day,Sensor_1,Sensor_2,Sensor_3,Sensor_4,Sensor_5,Sensor_6,Sensor_7,Sensor_8,Sensor_9,Sensor_10,Mean_Value,Variance,Target
0,Fresh,0,0.952173,0.598617,0.606477,0.615230,0.597658,0.597659,0.615792,0.607674,0.595305,0.605426,0.604481,0.000047,Fresh_Day0
1,Fresh,0,0.929555,0.595343,0.602420,0.580867,0.582751,0.594377,0.589872,0.603142,0.590920,0.585877,0.592093,0.000051,Fresh_Day0
2,Fresh,0,0.974999,0.597742,0.600675,0.585753,0.594556,0.601109,0.588490,0.603757,0.593994,0.597083,0.597782,0.000060,Fresh_Day0
3,Fresh,0,0.926297,0.618523,0.599865,0.589423,0.608225,0.587792,0.602089,0.580403,0.586718,0.601969,0.596899,0.000118,Fresh_Day0
4,Fresh,0,0.957868,0.601714,0.598844,0.596989,0.585215,0.592802,0.595394,0.610571,0.603436,0.582370,0.597472,0.000073,Fresh_Day0

In [82]:
df=pd.read_csv('CollegePlacement.csv')

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

In [85]:
# scaling 1
from sklearn.preprocessing import MinMaxScaler
minmaxscaler=MinMaxScaler()
for col in df.columns:
    if df[col].dtype!='object':
        df[col]=minmaxscaler.fit_transform(df[[col]])

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  float64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  float64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  float64
 7   Communication_Skills    10000 non-null  float64
 8   Projects_Completed      10000 non-null  float64
 9   Placement               10000 non-null  object
dtypes: float64(7), object(3)
memory usage: 781.4+ KB

In [86]:
df.head(10)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,0.564103,0.322,0.293919,0.777778,No,0.8,0.777778,0.8,No
1,CLG0061,0.478632,0.104,0.140203,0.777778,No,0.7,0.777778,0.0,No
2,CLG0036,0.581197,0.072,0.217905,0.888889,No,0.3,0.000000,0.2,No
3,CLG0055,0.692308,0.094,0.204392,0.555556,Yes,0.1,0.555556,0.2,No
4,CLG0004,0.470085,0.582,0.532095,0.666667,No,0.8,1.000000,0.4,No
5,CLG0015,0.470085,0.052,0.131757,0.666667,No,0.5,0.777778,0.0,No
6,CLG0071,0.700855,0.336,0.344595,0.444444,No,0.7,0.777778,0.4,Yes
7,CLG0096,0.598291,0.754,0.712838,0.666667,No,0.3,0.000000,0.4,Yes
8,CLG0097,0.435897,0.294,0.302365,0.888889,No,0.7,0.777778,1.0,No
9,CLG0057,0.572650,0.764,0.685811,0.333333,No,0.5,0.888889,0.2,No

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  float64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  float64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  float64
 7   Communication_Skills    10000 non-null  float64
 8   Projects_Completed      10000 non-null  float64
 9   Placement               10000 non-null  object
dtypes: float64(7), object(3)
memory usage: 781.4+ KB

In [87]:
# scaling 2
num_col=df.select_dtypes(include=['int64', 'float64']).columns

In [88]:
num_col

Index(['IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Extra_Curricular_Score', 'Communication_Skills', 'Projects_Completed'],
      dtype='object')

In [89]:
df[num_col]=minmaxscaler.fit_transform(df[num_col])

In [90]:
df.head(10)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,0.564103,0.322,0.293919,0.777778,No,0.8,0.777778,0.8,No
1,CLG0061,0.478632,0.104,0.140203,0.777778,No,0.7,0.777778,0.0,No
2,CLG0036,0.581197,0.072,0.217905,0.888889,No,0.3,0.000000,0.2,No
3,CLG0055,0.692308,0.094,0.204392,0.555556,Yes,0.1,0.555556,0.2,No
4,CLG0004,0.470085,0.582,0.532095,0.666667,No,0.8,1.000000,0.4,No
5,CLG0015,0.470085,0.052,0.131757,0.666667,No,0.5,0.777778,0.0,No
6,CLG0071,0.700855,0.336,0.344595,0.444444,No,0.7,0.777778,0.4,Yes
7,CLG0096,0.598291,0.754,0.712838,0.666667,No,0.3,0.000000,0.4,Yes
8,CLG0097,0.435897,0.294,0.302365,0.888889,No,0.7,0.777778,1.0,No
9,CLG0057,0.572650,0.764,0.685811,0.333333,No,0.5,0.888889,0.2,No

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  float64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  float64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  float64
 7   Communication_Skills    10000 non-null  float64
 8   Projects_Completed      10000 non-null  float64
 9   Placement               10000 non-null  object
dtypes: float64(7), object(3)
memory usage: 781.4+ KB

# #Nested if bo‘yicha 10 ta masala

In [ ]:
#1 Foydalanuvchidan son kiriting. Agar musbat bo‘lsa, uni juft yoki toqligini aniqlang.
a=int(input('soni kiriting'))
if a>0:
    if a%2==0:
        print('juft')
    else:
            print('toq')
else:
    print('son manfiy musbat son kiriting')

son manfiy musbat son kiriting

In [ ]:
2# Foydalanuvchidan yoshini so‘rang. Agar 18 yoki undan katta bo‘lsa, yana tekshirib 65 dan kichik bo‘lsa → "Katta yoshli", bo‘lmasa "Qari".
a=int(input('yoshingiz nechchida'))
if a>18:
    if 18<a<65:
        print('Katta yoshli')
    else:

        print('Qari')
else:
    print('siz hali yosh bolasiz')

Qari

In [ ]:
#3 Uchta son kiriting. Ichma-ich if yordamida eng kattasini toping.
a=int(input("1-sonni kiriting "))
b=int(input("2-sonni kiriting "))
c=int(input("3-sonni kiriting "))
if a > b:
    if a > c:
        eng_katta = a
    else:
        eng_katta = c
else:
    if b > c:
        eng_katta = b
    else:
        eng_katta = c

print("Eng katta son:", eng_katta)

Eng katta son: 44

In [ ]:
#4 Bitta belgi kiriting. Agar u harf bo‘lsa, yana tekshirib unli yoki undosh ekanligini aniqlang.
a=input('belgi kiriting:')
if len(a) == 1 and a.isalpha():
    vowels = "aeiouAEIOU"
    if a in vowels:
        print("Bu unli harf")
    else:
        print("Bu undosh harf")
else:
    print("Bunday harf alifboda yo'q yoki 1 tadan ko'p belgi kiritildi")

Bu undosh harf

In [ ]:
#5 Foydalanuvchidan imtihon bahosini kiriting. Agar baho ≥ 50 → "O‘tdi", bo‘lmasa "Yi qildi". Agar o‘tdi va baho ≥ 90 bo‘lsa → "A'lo".
a=int(input('bahoni kiriting:'))
if a>50:
    if 90>a>50:
       print('otdi')
    else:
        print('alo')
else:
    print('yiqildi')

yiqildi

In [134]:
#6 Son kiriting. Agar son 2 ga bo‘linsa, yana tekshirib 3 ga ham bo‘linishini aniqlang.
a=int(input('sonni kiriting'))
if a%2==0:
    print('bu son ikkiga bolinadi')
    if a % 3 == 0:
        print('uchga ham bolinadi')
else:
    print('bu son ikkiga bolinmaydi')

bu son ikkiga bolinadi
uchga ham bolinadi

In [148]:
#7 Haroratni kiriting. Agar 0 dan katta bo‘lsa → "Muzlashdan yuqori". Agar 30 dan katta bo‘lsa → "Issiq". Agar 0 dan kichik bo‘lsa → "Muzlash" deb chiqaring.
a=int(input('haroratni kiriting:'))
if a>0:
    if a>30:
       print('issiq')
    else:
        print('muzlashdan yuqori')
else:
    print('muzlash')

muzlashdan yuqori

In [160]:
#8 Svetofor rangini kiriting (qizil, sariq, yashil). Agar yashil → "Yur", agar qizil → "To‘xta", agar sariq → "Kut".
svetafor = input('Rangni yozing:')
if svetafor == "yashil":
    print('yur')
elif svetafor == "qizil":
    print('toxta')
elif svetafor == 'sariq':
    print('kut')
else:
    print('bunday rang yuq')

bunday rang yuq

In [169]:
#9 Bir yilni kiriting. Agar yil 4 ga bo‘linsa va 100 ga bo‘linmasa yoki 400 ga bo‘linsa → "Kabisa yili", bo‘lmasa "Oddiy yil".
a = int(input("Yilni kiriting: "))

if a % 4 == 0:
    if a % 100 != 0:
        print("Kabisa yili")
    else:
        if a % 400 == 0:
            print("Kabisa yili")
        else:
            print("Oddiy yil")

else:
    print("Oddiy yil")

Kabisa yili

In [179]:
# Ikki son kiriting. Agar birinchi > ikkinchi bo‘lsa → "Birinchi katta", agar teng bo‘lsa → "Teng", aks holda "Ikkinchi katta".
a = int(input('1-sonni kiriting:'))
b = int(input('2-sonni kiriting:'))
if a > b:
    print('1-son katta')
elif a < b:
        print('2-son katta')
else:
    print('bu sonlar teng')

2-son katta

# #List comprehension bo‘yicha 10 ta masala

In [180]:
#1 1 dan 10 gacha bo‘lgan sonlar ro‘yxatini tuzing.
[i for i in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [197]:
#2 1 dan 10 gacha bo‘lgan sonlarning kvadratlari ro‘yxatini yarating.
[i**2 for i in range(1,11) ]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [198]:
#3 1 dan 20 gacha bo‘lgan juft sonlar ro‘yxatini tuzing.
[i for i in range(1,21) if i%2==0]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [204]:
#4 1 dan 10 gacha sonlar uchun "Juft" yoki "Toq" degan yozuvlardan iborat ro‘yxat tuzing (if else bilan).
['juft' if i%2==0 else 'toq'  for i in range(1,10)]

['toq', 'juft', 'toq', 'juft', 'toq', 'juft', 'toq', 'juft', 'toq']

In [205]:
#5 1 dan 20 gacha bo‘lgan sonlardan faqat 3 ga bo‘linadigan sonlar ro‘yxatini yarating.
[i for i in range(1,21) if i%3==0]

[3, 6, 9, 12, 15, 18]

In [207]:
#6 1 dan 10 gacha sonlar ro‘yxatini tuzing, agar son 2 ga bo‘linsa "Ikki" deb yozing, bo‘lmasa sonning o‘zini yozing.
['ikki' if i%2==0 else i for i in range(1,11)]

[1, 'ikki', 3, 'ikki', 5, 'ikki', 7, 'ikki', 9, 'ikki']

In [208]:
#7 Berilgan so‘zlar ro‘yxatidan faqat uzunligi 4 dan katta bo‘lgan so‘zlarni ajratib oling.
sozlar = ["kitob", "olma", "qush", "daraxt", "uy", "kompyuter"]

natija = [soz for soz in sozlar if len(soz) > 4]

print(natija)

['kitob', 'daraxt', 'kompyuter']

In [211]:
#8 Berilgan so‘zlar ro‘yxatini har bir so‘zni katta harflar bilan yozilgan ko‘rinishga aylantiring.
sozlar = ['ilm', 'gul', 'nok']

natija = [soz.upper() for soz in sozlar]
print(natija)

['ILM', 'GUL', 'NOK']

In [ ]:
#9 1 dan 30 gacha bo‘lgan sonlardan faqat 5 ga bo‘linadigan sonlarni tanlab ro‘yxat tuzing.
[i for i in range(1,31) if i%5==0]

[5, 10, 15, 20, 25, 30]

In [213]:
#10 1 dan 15 gacha sonlardan: agar son juft bo‘lsa → sonning kvadrati, agar toq bo‘lsa → sonning kubini ro‘yxatga yozing.
natija = [i**2 if i % 2 == 0 else i**3 for i in range(1, 16)]
print(natija)

[1, 4, 27, 16, 125, 36, 343, 64, 729, 100, 1331, 144, 2197, 196, 3375]