# for loop orqali missing qiymatlarni tozalash

In [1]:
import pandas as pd

In [17]:
df=pd.read_csv('house_prices_dataset reg.csv')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           9998 non-null   float64
 1   num_rooms             10000 non-null  int64
 2   age                   9999 non-null   float64
 3   distance_to_city(km)  9998 non-null   float64
 4   price                 9999 non-null   float64
dtypes: float64(4), int64(1)
memory usage: 390.8 KB

In [19]:
df.isnull().sum()

square_feet             2
num_rooms               0
age                     1
distance_to_city(km)    2
price                   1
dtype: int64

In [20]:
df.head()

   square_feet  num_rooms   age  distance_to_city(km)          price
0  2248.357077          3  92.0             22.997972  200374.090410
1  1930.867849          2  22.0             13.984254  268784.847337
2  2323.844269          6  33.0             21.500945  315020.857676
3  2761.514928          3  63.0             10.343638  355111.468459
4  1882.923313          7  54.0             25.485200  234197.123903

In [21]:
for col in df.columns:
    print(col)

square_feet
num_rooms
age
distance_to_city(km)
price

In [22]:
#for + if
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0], inplace=True)
        else:
                df[col].fillna(df[col].mean(), inplace=True)

C:\Users\hamid\AppData\Local\Temp\ipykernel_37760\1536939481.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           10000 non-null  float64
 1   num_rooms             10000 non-null  int64
 2   age                   10000 non-null  float64
 3   distance_to_city(km)  10000 non-null  float64
 4   price                 10000 non-null  float64
dtypes: float64(4), int64(1)
memory usage: 390.8 KB

In [24]:
df.nunique()

square_feet              9987
num_rooms                   6
age                       101
distance_to_city(km)     9999
price                   10000
dtype: int64

# For + Encoding

In [2]:
df=pd.read_csv('air_quality_dataset.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PM2.5           496 non-null    float64
 1   PM10            499 non-null    float64
 2   NOx             497 non-null    float64
 3   NO2             497 non-null    float64
 4   SO2             495 non-null    float64
 5   VOCs            493 non-null    float64
 6   CO              495 non-null    float64
 7   CO2             494 non-null    float64
 8   CH4             489 non-null    float64
 9   Temperature     495 non-null    float64
 10  Humidity        500 non-null    float64
 11  Wind_Direction  500 non-null    int64
 12  Location_Type   500 non-null    object
 13  Source_Label    500 non-null    object
dtypes: float64(11), int64(1), object(2)
memory usage: 54.8+ KB

In [4]:
df.nunique()

PM2.5             496
PM10              499
NOx               497
NO2               497
SO2               495
VOCs              493
CO                495
CO2               494
CH4               489
Temperature       495
Humidity          500
Wind_Direction    267
Location_Type       3
Source_Label        3
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
encoder=LabelEncoder()

In [7]:
encoder

LabelEncoder()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PM2.5           496 non-null    float64
 1   PM10            499 non-null    float64
 2   NOx             497 non-null    float64
 3   NO2             497 non-null    float64
 4   SO2             495 non-null    float64
 5   VOCs            493 non-null    float64
 6   CO              495 non-null    float64
 7   CO2             494 non-null    float64
 8   CH4             489 non-null    float64
 9   Temperature     495 non-null    float64
 10  Humidity        500 non-null    float64
 11  Wind_Direction  500 non-null    int64
 12  Location_Type   500 non-null    object
 13  Source_Label    500 non-null    object
dtypes: float64(11), int64(1), object(2)
memory usage: 54.8+ KB

In [9]:
df.nunique()

PM2.5             496
PM10              499
NOx               497
NO2               497
SO2               495
VOCs              493
CO                495
CO2               494
CH4               489
Temperature       495
Humidity          500
Wind_Direction    267
Location_Type       3
Source_Label        3
dtype: int64

In [10]:

df.isnull().sum()

PM2.5              4
PM10               1
NOx                3
NO2                3
SO2                5
VOCs               7
CO                 5
CO2                6
CH4               11
Temperature        5
Humidity           0
Wind_Direction     0
Location_Type      0
Source_Label       0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=3:
            dummies=pd.get_dummies(df[col], prefix=col, dtype=int)
            df=pd.concat([df.drop(columns=col), dummies], axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PM2.5                         496 non-null    float64
 1   PM10                          499 non-null    float64
 2   NOx                           497 non-null    float64
 3   NO2                           497 non-null    float64
 4   SO2                           495 non-null    float64
 5   VOCs                          493 non-null    float64
 6   CO                            495 non-null    float64
 7   CO2                           494 non-null    float64
 8   CH4                           489 non-null    float64
 9   Temperature                   495 non-null    float64
 10  Humidity                      500 non-null    float64
 11  Wind_Direction                500 non-null    int64
 12  Location_Type_Industrial      500 non-null    int64
 13  Location_Type_Rural           500 non-null    int64
 14  Location_Type_Urban           500 non-null    int64
 15  Source_Label_Biomass Burning  500 non-null    int64
 16  Source_Label_Industrial       500 non-null    int64
 17  Source_Label_Vehicular        500 non-null    int64
dtypes: float64(11), int64(7)
memory usage: 70.4 KB

# Scalling qilish

In [4]:
import pandas as pd

In [2]:
import pandas as pd

df = pd.read_csv("house_prices_dataset reg.csv")
print(df.head())

   square_feet  num_rooms   age  distance_to_city(km)          price
0  2248.357077          3  92.0             22.997972  200374.090410
1  1930.867849          2  22.0             13.984254  268784.847337
2  2323.844269          6  33.0             21.500945  315020.857676
3  2761.514928          3  63.0             10.343638  355111.468459
4  1882.923313          7  54.0             25.485200  234197.123903

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           9998 non-null   float64
 1   num_rooms             10000 non-null  int64
 2   age                   9999 non-null   float64
 3   distance_to_city(km)  9998 non-null   float64
 4   price                 9999 non-null   float64
dtypes: float64(4), int64(1)
memory usage: 390.8 KB

In [4]:
df.nunique()

square_feet             9986
num_rooms                  6
age                      100
distance_to_city(km)    9998
price                   9999
dtype: int64

# StandardScaler

In [9]:
# StandardScaler

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
standardscaler=StandardScaler()

In [10]:
standardscaler

StandardScaler()

In [5]:
df.head()

   square_feet  num_rooms   age  distance_to_city(km)          price
0  2248.357077          3  92.0             22.997972  200374.090410
1  1930.867849          2  22.0             13.984254  268784.847337
2  2323.844269          6  33.0             21.500945  315020.857676
3  2761.514928          3  63.0             10.343638  355111.468459
4  1882.923313          7  54.0             25.485200  234197.123903

In [11]:
df['age']=standardscaler.fit_transform(df[['age']])

In [12]:
df.head()

   square_feet  num_rooms       age  distance_to_city(km)          price
0  2248.357077          3  1.465474             22.997972  200374.090410
1  1930.867849          2 -0.949058             13.984254  268784.847337
2  2323.844269          6 -0.569631             21.500945  315020.857676
3  2761.514928          3  0.465168             10.343638  355111.468459
4  1882.923313          7  0.154728             25.485200  234197.123903

# MinMax Scaler

In [13]:
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler()

In [14]:
df['price']=minmax.fit_transform(df[['price']])

In [15]:
df.head()

   square_feet  num_rooms       age  distance_to_city(km)     price
0  2248.357077          3  1.465474             22.997972  0.391631
1  1930.867849          2 -0.949058             13.984254  0.482147
2  2323.844269          6 -0.569631             21.500945  0.543324
3  2761.514928          3  0.465168             10.343638  0.596369
4  1882.923313          7  0.154728             25.485200  0.436383

# mmm

In [16]:
from sklearn.preprocessing import RobustScaler
robust=RobustScaler()

In [17]:
df['square_feet']=robust.fit_transform(df[['square_feet']])

In [18]:
df.head()

   square_feet  num_rooms       age  distance_to_city(km)     price
0     0.371508          3  1.465474             22.997972  0.391631
1    -0.100944          2 -0.949058             13.984254  0.482147
2     0.483839          6 -0.569631             21.500945  0.543324
3     1.135131          3  0.465168             10.343638  0.596369
4    -0.172290          7  0.154728             25.485200  0.436383