# One-Hot Encoding

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("air_quality_dataset.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PM2.5           500 non-null    float64
 1   PM10            500 non-null    float64
 2   NOx             500 non-null    float64
 3   NO2             500 non-null    float64
 4   SO2             500 non-null    float64
 5   VOCs            500 non-null    float64
 6   CO              500 non-null    float64
 7   CO2             500 non-null    float64
 8   CH4             500 non-null    float64
 9   Temperature     500 non-null    float64
 10  Humidity        500 non-null    float64
 11  Wind_Direction  500 non-null    int64
 12  Location_Type   500 non-null    object
 13  Source_Label    500 non-null    object
dtypes: float64(11), int64(1), object(2)
memory usage: 54.8+ KB

In [5]:
df.head()

,PM2.5,PM10,NOx,NO2,SO2,VOCs,CO,CO2,CH4,Temperature,Humidity,Wind_Direction,Location_Type,Source_Label
0,39.967142,57.926035,116.192213,55.230299,4.531693,75.317261,2.789606,427.674347,1.706105,31.085120,45.454749,276,Urban,Vehicular
1,101.935672,150.774299,76.826826,79.051618,18.744780,145.083987,1.966569,529.739619,2.492663,33.711103,60.798212,134,Industrial,Industrial
2,70.996192,138.948796,158.731020,60.466604,14.892239,145.147338,2.626446,499.889443,2.431165,33.778698,54.875669,1,Industrial,Industrial
3,28.464728,63.643900,25.385343,15.333286,7.647429,130.022319,1.779360,388.283712,1.818563,31.565877,67.113319,251,Rural,Biomass Burning
4,78.265276,113.977926,105.644340,59.202337,17.696806,181.713667,3.240533,464.739197,2.597225,32.229835,37.236519,326,Industrial,Industrial

In [6]:
df['Location_Type']

0           Urban
1      Industrial
2      Industrial
3           Rural
4      Industrial
          ...
495         Rural
496         Rural
497         Rural
498         Rural
499         Rural
Name: Location_Type, Length: 500, dtype: object

In [7]:
df[['Wind_Direction', 'Source_Label']]

     Wind_Direction     Source_Label
0               276        Vehicular
1               134       Industrial
2                 1       Industrial
3               251  Biomass Burning
4               326       Industrial
..              ...              ...
495             289  Biomass Burning
496             270  Biomass Burning
497             185  Biomass Burning
498             272  Biomass Burning
499             239  Biomass Burning

[500 rows x 2 columns]

In [8]:
df['Source_Label'].nunique()

3

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PM2.5           500 non-null    float64
 1   PM10            500 non-null    float64
 2   NOx             500 non-null    float64
 3   NO2             500 non-null    float64
 4   SO2             500 non-null    float64
 5   VOCs            500 non-null    float64
 6   CO              500 non-null    float64
 7   CO2             500 non-null    float64
 8   CH4             500 non-null    float64
 9   Temperature     500 non-null    float64
 10  Humidity        500 non-null    float64
 11  Wind_Direction  500 non-null    int64
 12  Location_Type   500 non-null    object
 13  Source_Label    500 non-null    object
dtypes: float64(11), int64(1), object(2)
memory usage: 54.8+ KB

In [10]:
df['Source_Label'].fillna(df['Source_Label'].mode()[0],inplace=True)

C:\Users\hamid\AppData\Local\Temp\ipykernel_34560\331218173.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Source_Label'].fillna(df['Source_Label'].mode()[0],inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PM2.5           500 non-null    float64
 1   PM10            500 non-null    float64
 2   NOx             500 non-null    float64
 3   NO2             500 non-null    float64
 4   SO2             500 non-null    float64
 5   VOCs            500 non-null    float64
 6   CO              500 non-null    float64
 7   CO2             500 non-null    float64
 8   CH4             500 non-null    float64
 9   Temperature     500 non-null    float64
 10  Humidity        500 non-null    float64
 11  Wind_Direction  500 non-null    int64
 12  Location_Type   500 non-null    object
 13  Source_Label    500 non-null    object
dtypes: float64(11), int64(1), object(2)
memory usage: 54.8+ KB

In [12]:
dummies=pd.get_dummies(df['Source_Label'],prefix='col',dtype=int)

In [13]:
dummies

     col_Biomass Burning  col_Industrial  col_Vehicular
0                      0               0              1
1                      0               1              0
2                      0               1              0
3                      1               0              0
4                      0               1              0
..                   ...             ...            ...
495                    1               0              0
496                    1               0              0
497                    1               0              0
498                    1               0              0
499                    1               0              0

[500 rows x 3 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PM2.5           500 non-null    float64
 1   PM10            500 non-null    float64
 2   NOx             500 non-null    float64
 3   NO2             500 non-null    float64
 4   SO2             500 non-null    float64
 5   VOCs            500 non-null    float64
 6   CO              500 non-null    float64
 7   CO2             500 non-null    float64
 8   CH4             500 non-null    float64
 9   Temperature     500 non-null    float64
 10  Humidity        500 non-null    float64
 11  Wind_Direction  500 non-null    int64
 12  Location_Type   500 non-null    object
 13  Source_Label    500 non-null    object
dtypes: float64(11), int64(1), object(2)
memory usage: 54.8+ KB

In [15]:
df=pd.concat([df.drop(columns='Source_Label'),dummies],axis=1)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PM2.5                500 non-null    float64
 1   PM10                 500 non-null    float64
 2   NOx                  500 non-null    float64
 3   NO2                  500 non-null    float64
 4   SO2                  500 non-null    float64
 5   VOCs                 500 non-null    float64
 6   CO                   500 non-null    float64
 7   CO2                  500 non-null    float64
 8   CH4                  500 non-null    float64
 9   Temperature          500 non-null    float64
 10  Humidity             500 non-null    float64
 11  Wind_Direction       500 non-null    int64
 12  Location_Type        500 non-null    object
 13  col_Biomass Burning  500 non-null    int64
 14  col_Industrial       500 non-null    int64
 15  col_Vehicular        500 non-null    int64
dtypes: float64(11), int64(4), object(1)
memory usage: 62.6+ KB

In [17]:
df.nunique()

PM2.5                  500
PM10                   500
NOx                    500
NO2                    500
SO2                    500
VOCs                   500
CO                     500
CO2                    500
CH4                    500
Temperature            500
Humidity               500
Wind_Direction         267
Location_Type            3
col_Biomass Burning      2
col_Industrial           2
col_Vehicular            2
dtype: int64

In [18]:
df['col_Industrial']

0      0
1      1
2      1
3      0
4      1
      ..
495    0
496    0
497    0
498    0
499    0
Name: col_Industrial, Length: 500, dtype: int64

In [19]:
pd.get_dummies

<function pandas.core.reshape.encoding.get_dummies(data, prefix=None, prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_', dummy_na: 'bool' = False, columns=None, sparse: 'bool' = False, drop_first: 'bool' = False, dtype: 'NpDtype | None' = None) -> 'DataFrame'>

In [20]:
#Soxta(dummies) ustunlar yaratish(1-bosqich)
dummies=pd.get_dummies(df['col_Industrial'],prefix='ustun',dtype=int)

In [21]:
dummies

     ustun_0  ustun_1
0          1        0
1          0        1
2          0        1
3          1        0
4          0        1
..       ...      ...
495        1        0
496        1        0
497        1        0
498        1        0
499        1        0

[500 rows x 2 columns]

In [23]:
#2-bosqich(datasetni birlashtirish)
df=pd.concat([df.drop(columns='col_Industrial'),dummies],axis=1)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PM2.5                500 non-null    float64
 1   PM10                 500 non-null    float64
 2   NOx                  500 non-null    float64
 3   NO2                  500 non-null    float64
 4   SO2                  500 non-null    float64
 5   VOCs                 500 non-null    float64
 6   CO                   500 non-null    float64
 7   CO2                  500 non-null    float64
 8   CH4                  500 non-null    float64
 9   Temperature          500 non-null    float64
 10  Humidity             500 non-null    float64
 11  Wind_Direction       500 non-null    int64
 12  Location_Type        500 non-null    object
 13  col_Biomass Burning  500 non-null    int64
 14  col_Vehicular        500 non-null    int64
 15  ustun_0              500 non-null    int64
 16  ustun_1              500 non-null    int64
dtypes: float64(11), int64(5), object(1)
memory usage: 66.5+ KB