# 7-task

In [ ]:
# Ixtiyoriy listda berilgan sonlarni yigindisini toping
# Ixtiyoriy listda berilgan sonlarni kopaytmasini toping
# Ixtiyoriy listda berilgan just sonlarni yigindisini toping
# Ixtiyoriy listda berilgan toq sonlarni yigindisini toping
# Ixtiyoriy listda berilgan musbat va toq sonlarni yigindisini toping
# Ixtiyoriy listda berilgan musbat lekin toq bolmagan sonlarni sonlarni yigindisini toping
# Ixtiyoriy listda berilgan musbat va toq va 3 ga bolinadigan  sonlarni yigindisini toping
# Ixtiyoriy listda berilgan manfiy va 2  xonalari  sonlarni yigindisini toping
# Ixtiyoriy listda berilgan 5ga  karrali manfiy  sonlarni yigindisini toping
# Ixtiyoriy listda berilgan 5ga  karrali manfiy  sonlarni kopaytmasini toping

In [2]:
# Ixtiyoriy listda berilgan sonlarni yigindisini toping
# Ixtiyoriy list
numbers = [3, -2, 8, 22, 14]
yigindi=0
for son in numbers:
    yigindi +=son
print('sonlar yigindisi:', yigindi)

sonlar yigindisi: 45

In [7]:
# Ixtiyoriy listda berilgan sonlarni kopaytmasini toping
# Ixtiyoriy list
numbers = [3, 2, 7, 2, 4]
kopaytma=1
for son in numbers:
    kopaytma *=son
print('sonlar kopaytmasi:', kopaytma)

sonlar kopaytmasi: 336

In [8]:
# Ixtiyoriy listda berilgan just sonlarni yigindisini toping
# Ixtiyoriy list
numbers = [36, 12, 70, 24, 4]
yigindi=0
for son in numbers:
    if son % 2 == 0:
        yigindi += son
        print('juft sonlar yigindisi:', yigindi)

juft sonlar yigindisi: 36
juft sonlar yigindisi: 48
juft sonlar yigindisi: 118
juft sonlar yigindisi: 142
juft sonlar yigindisi: 146

In [9]:
# Ixtiyoriy listda berilgan toq sonlarni yigindisini toping
# Ixtiyoriy list
numbers = [33, 11, 7, 5, 41]
yigindi=0
for son in numbers:
    if son % 2 == 1:
        yigindi += son
        print('toq sonlar yigindisi:', yigindi)

toq sonlar yigindisi: 33
toq sonlar yigindisi: 44
toq sonlar yigindisi: 51
toq sonlar yigindisi: 56
toq sonlar yigindisi: 97

In [12]:
# Ixtiyoriy listda berilgan musbat va toq sonlarni yigindisini toping
# Ixtiyoriy list
numbers = [3, 11, 17, 13, 41]
yigindi=0
for son in numbers:
    if son % 2 == 1 and son > 0:
        yigindi += son
        print('musbat va toq sonlar yigindisi :', yigindi)

musbat va toq sonlar yigindisi : 3
musbat va toq sonlar yigindisi : 14
musbat va toq sonlar yigindisi : 31
musbat va toq sonlar yigindisi : 44
musbat va toq sonlar yigindisi : 85

In [13]:
# Ixtiyoriy listda berilgan musbat lekin toq bolmagan sonlarni yigindisini toping
# Ixtiyoriy list
numbers = [6, 12, 10, 18, 16]
yigindi=0
for son in numbers:
    if son % 2 == 0 and son > 0:
        yigindi += son
        print('musbat lekin toq bolmagan sonlarni :', yigindi)

musbat va toq sonlar yigindisi : 6
musbat va toq sonlar yigindisi : 18
musbat va toq sonlar yigindisi : 28
musbat va toq sonlar yigindisi : 46
musbat va toq sonlar yigindisi : 62

In [25]:
# Ixtiyoriy listda berilgan musbat va toq va 3 ga bolinadigan  sonlarni yigindisini toping
# Ixtiyoriy list
numbers = [3, 15, 9, 18, 21]
yigindi=0
for son in numbers:
    if son > 0 and son % 2 == 1 and son % 3 == 0 :
        yigindi += son
        print('musbat va toq va 3 ga bolinadigan sonlarni yigindisi:', yigindi)

musbat va toq va 3 ga bolinadigan sonlarni yigindisi: 3
musbat va toq va 3 ga bolinadigan sonlarni yigindisi: 18
musbat va toq va 3 ga bolinadigan sonlarni yigindisi: 27
musbat va toq va 3 ga bolinadigan sonlarni yigindisi: 48

In [26]:
# Ixtiyoriy listda berilgan manfiy va 2  xonalari  sonlarni yigindisini toping
# Ixtiyoriy list
numbers = [-3, -15, -9, -18, -21]
yigindi=0
for son in numbers:
    if son < 0 and -99 < son < -9  :
        yigindi += son
        print('manfiy va 2  xonalari  sonlarni yigindisi :', yigindi)

manfiy va 2  xonalari  sonlarni yigindisi : -15
manfiy va 2  xonalari  sonlarni yigindisi : -33
manfiy va 2  xonalari  sonlarni yigindisi : -54

In [29]:
# Ixtiyoriy listda berilgan 5ga  karrali manfiy  sonlarni yigindisini toping
# Ixtiyoriy list
numbers = [-5, -15, -30, -10, -20]
yigindi=0
for son in numbers:
    if son % 5 ==0 and -99 < son < -9  :
        yigindi += son
        print('5ga  karrali manfiy  sonlarni yigindisi :', yigindi)

5ga  karrali manfiy  sonlarni yigindisi : -15
5ga  karrali manfiy  sonlarni yigindisi : -45
5ga  karrali manfiy  sonlarni yigindisi : -55
5ga  karrali manfiy  sonlarni yigindisi : -75

In [30]:
# Ixtiyoriy listda berilgan 5ga  karrali manfiy  sonlarni kopaytmasini toping
# Ixtiyoriy list
numbers = [-5, -15, -30, -10, -20]
kopaytma=1
for son in numbers:
    if son % 5 == 0 and -99 < son < -9  :
        kopaytma *= son
        print('5ga  karrali manfiy  sonlarni kopaytmasi :', kopaytma)

5ga  karrali manfiy  sonlarni kopaytmasi : -15
5ga  karrali manfiy  sonlarni kopaytmasi : 450
5ga  karrali manfiy  sonlarni kopaytmasi : -4500
5ga  karrali manfiy  sonlarni kopaytmasi : 90000

# for lop orqali missing qiymatlarni toldirish

In [5]:
import pandas as pd

In [7]:
df=pd.read_csv('water_potability.csv')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2784 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

In [9]:
df.isnull().sum()

ph                 492
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [10]:
df.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,NaN,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [ ]:
df.head(

)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

#for loop orqali ustunlarni alohida ajratish

In [12]:
for col in df.columns:
    print(col)

ph
Hardness
Solids
Chloramines
Sulfate
Conductivity
Organic_carbon
Trihalomethanes
Turbidity
Potability

In [15]:
#for + if
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0], inplace=True)
        else:
                df[col].fillna(df[col].mean(), inplace=True)

C:\Users\hamid\AppData\Local\Temp\ipykernel_3236\25842872.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               3276 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          3276 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3276 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

# 5 ta usulda toldirish

In [17]:
import pandas as pd

In [28]:
df=pd.read_csv('Employers_data reg.csv')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       10000 non-null  int64
 1   Name              9995 non-null   object
 2   Age               10000 non-null  int64
 3   Gender            9994 non-null   object
 4   Department        9998 non-null   object
 5   Job_Title         10000 non-null  object
 6   Experience_Years  9996 non-null   float64
 7   Education_Level   10000 non-null  object
 8   Location          10000 non-null  object
 9   Salary            10000 non-null  int64
dtypes: float64(1), int64(3), object(6)
memory usage: 781.4+ KB

In [29]:
for col in df.columns:
    print(col)

Employee_ID
Name
Age
Gender
Department
Job_Title
Experience_Years
Education_Level
Location
Salary

In [30]:
df.isnull().sum()

Employee_ID         0
Name                5
Age                 0
Gender              6
Department          2
Job_Title           0
Experience_Years    4
Education_Level     0
Location            0
Salary              3
dtype: int64

In [33]:
# mean orqali toldirish
df['Salary'].fillna(df['Salary'].mean(),inplace=True)

C:\Users\hamid\AppData\Local\Temp\ipykernel_3236\522801370.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [34]:
# mode orqali toldirish
df['Salary'].fillna(df['Salary'].mode()[0],inplace=True)

C:\Users\hamid\AppData\Local\Temp\ipykernel_3236\3611414121.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mode()[0],inplace=True)

In [ ]:
# median orqali toldirish
df['Salary'].fillna('',inplace=True)

C:\Users\hamid\AppData\Local\Temp\ipykernel_3236\3465007235.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(),inplace=True)

In [37]:
# fixed qiymat berish  orqali toldirish
df['Salary'].fillna(9000.0,inplace=True)

In [36]:
df['Salary']

0        90000.0
1       195000.0
2        35000.0
3        75000.0
4        70000.0
          ...
9995    185000.0
9996    165000.0
9997    200000.0
9998    135000.0
9999     70000.0
Name: Salary, Length: 10000, dtype: float64

In [38]:
# drop tashab yuborish  orqali toldirish
df.dropna(inplace=True)

# Encoding

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9986 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       9986 non-null   int64
 1   Name              9986 non-null   object
 2   Age               9986 non-null   int64
 3   Gender            9986 non-null   object
 4   Department        9986 non-null   object
 5   Job_Title         9986 non-null   object
 6   Experience_Years  9986 non-null   float64
 7   Education_Level   9986 non-null   object
 8   Location          9986 non-null   object
 9   Salary            9986 non-null   float64
dtypes: float64(2), int64(2), object(6)
memory usage: 858.2+ KB

In [40]:
# one hot encoding
df['Name']

0         Merle Ingram
1           John Mayes
2         Carlos Wille
4        Paula Douglas
5       Michael Irving
             ...
9995     Thomas Rossin
9996     Christie King
9997     Alfred Keller
9998    Margaret Gomez
9999     Joan Sorensen
Name: Name, Length: 9986, dtype: object

In [41]:
df['Name'].nunique()

9855

In [42]:
dummies=pd.get_dummies(df['Name'], prefix='col',dtype = int)

In [43]:
dummies

,col_Aaron Biderman,col_Aaron Chaney,col_Aaron Davis,col_Aaron Defosses,col_Aaron Elerson,col_Aaron Hicks,col_Aaron Kirch,col_Aaron Krampitz,col_Aaron Leonard,col_Aaron Pennell,...,col_Yvonne Connors,col_Yvonne Gilbreath,col_Yvonne Monroe,col_Yvonne Smith,col_Zachary Allison,col_Zachary Bell,col_Zachary Lanser,col_Zachary Mcbride,col_Zachary Reese,col_Zulma Burke
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
df=pd.concat([df.drop(columns='Name'), dummies], axis=1)

In [46]:
df.nunique()

Employee_ID            9986
Age                      40
Gender                    2
Department                6
Job_Title                 5
                       ...
col_Zachary Bell          2
col_Zachary Lanser        2
col_Zachary Mcbride       2
col_Zachary Reese         2
col_Zulma Burke           2
Length: 9864, dtype: int64

# Label encoding

In [49]:
from sklearn.preprocessing import LabelEncoder

In [53]:
encoder=LabelEncoder()

In [54]:
encoder

LabelEncoder()

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9986 entries, 0 to 9999
Columns: 9864 entries, Employee_ID to col_Zulma Burke
dtypes: float64(2), int64(9857), object(5)
memory usage: 751.6+ MB

In [58]:
print(df.columns)

Index(['Employee_ID', 'Age', 'Gender', 'Department', 'Job_Title',
       'Experience_Years', 'Education_Level', 'Location', 'Salary',
       'col_Aaron Biderman',
       ...
       'col_Yvonne Connors', 'col_Yvonne Gilbreath', 'col_Yvonne Monroe',
       'col_Yvonne Smith', 'col_Zachary Allison', 'col_Zachary Bell',
       'col_Zachary Lanser', 'col_Zachary Mcbride', 'col_Zachary Reese',
       'col_Zulma Burke'],
      dtype='object', length=9864)

In [59]:
# Label encoding

df['Job_Title']=encoder.fit_transform(df['Job_Title'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9986 entries, 0 to 9999
Columns: 9864 entries, Employee_ID to col_Zulma Burke
dtypes: float64(2), int64(9858), object(4)
memory usage: 751.6+ MB